### ISSUE TITLE
Please upload your headshot to GitHub

### ISSUE THREAD

**Issue by philipmjohnson** [ics-portfolios/ics-portfolios.github.io#3]
so issue assignments show your face, not a random graphic. :)

**Comment by mckuok** [comment]
Can I not ... I don't like exposing my identity on the internet

**Comment by philipmjohnson** [comment]
This makes no sense: you already have a TechFolio and a LinkedIn profile with your headshot. Having your headshot in GitHub is going to make absolutely no difference privacy-wise for you.

The issue of internet identity and privacy is an interesting and important one.  There are some people I know who are in specialized security-related disciplines and who don't have LinkedIn, don't use Facebook, don't barely have a public email address, and this is directly related to their professional area.  However, that approach has significant negative professional consequences for anyone pursuing more typical computer science career paths. What I think you should focus on is creating the highest quality online presence possible.  Having a single headshot that you use uniformly helps people to create a better image of you (literally and figuratively).  It has minimal to no impact security-wise: the algorithms can put two and two together whether or not you have picture associated with your profile.
